[package]
name = "tinyusdz-sys"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Raw FFI bindings for tinyusdz"
links = "tinyusdz"
build = "build.rs"

[build-dependencies]
bindgen = "0.70"
cmake = "0.1"
